# config/config.yaml
metrics_dict:
  "SQL (Scaled quantile loss)": "SQL"
  "WQL (Weighted quantile loss)": "WQL"
  "MAE (Mean absolute error)": "MAE"
  "MAPE (Mean absolute percentage error)": "MAPE"
  "MASE (Mean absolute scaled error)": "MASE"
  "MSE (Mean squared error)": "MSE"
  "RMSE (Root mean squared error)": "RMSE"
  "RMSLE (Root mean squared logarithmic error)": "RMSLE"
  "RMSSE (Root mean squared scaled error)": "RMSSE"
  "SMAPE (Symmetric mean absolute percentage error)": "SMAPE"
  "WAPE (Weighted absolute percentage error)": "WAPE"

ag_models:
  "NaiveModel": "Базовая модель: прогноз = последнее наблюдение"
  "SeasonalNaiveModel": "Прогноз = последнее значение той же фазы сезона"
  "AverageModel": "Прогноз = среднее/квантиль"
  "SeasonalAverageModel": "Прогноз = среднее по тем же фазам сезона"
  "ZeroModel": "Прогноз = 0"
  "ETSModel": "Экспоненциальное сглаживание (ETS)"
  "AutoARIMAModel": "Автоматическая ARIMA"
  "AutoETSModel": "Автоматическая ETS"
  "AutoCESModel": "Комплексное экспоненциальное сглаживание (AIC)"
  "ThetaModel": "Theta"
  "ADIDAModel": "Intermittent demand (ADIDA)"
  "CrostonModel": "Intermittent demand (Croston)"
  "IMAPAModel": "Intermittent demand (IMAPA)"
  "NPTSModel": "Non-Parametric Time Series"
  "DeepARModel": "RNN (DeepAR)"
  "DLinearModel": "DLinear (убирает тренд)"
  "PatchTSTModel": "PatchTST (Transformer)"
  "SimpleFeedForwardModel": "Простая полносвязная сеть"
  "TemporalFusionTransformerModel": "LSTM + Transformer (TFT)"
  "TiDEModel": "Time series dense encoder"
  "WaveNetModel": "WaveNet (CNN)"
  "DirectTabularModel": "AutoGluon-Tabular (Direct)"
  "RecursiveTabularModel": "AutoGluon-Tabular (Recursive)"
  "Chronos": "Chronos Bolt model pretrained"


